import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { useSession } from 'next-auth/react';
import Header from '../components/Header'

export default function Home() {
  const { data: session, status } = useSession()
  const loading = status === "loading"
  return (
    <div className={styles.container}>
      <Head>
        <title>Basket Bananas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
      
      {loading && <div className={styles.title}>Loading...</div>}
           {
            session &&  <div>
               
              
               <p style={{ marginBottom: '10px' }}> Welcome, {session.user.name ?? session.user.email}</p> <br />
               <img src={session.user.image} alt="" className={styles.avatar} />
               <h1 className={styles.title}>
          Welcome to <a href="https://www.facebook.com/groups/530462118041572" target="_blank"
          rel="noopener noreferrer">Basket Bananas!</a>
        </h1>

        <p className={styles.description}>
          Feel free to email me on hzethraeus@gmail.com, <br/>if you find any errors on the page.
        </p>

        <div className={styles.grid}>
            <Link href="/fbFlow">
            <a className={styles.card}>
              <h2>Facebook Posts &rarr;</h2>
              <p>Check for new posts and sign up to play.</p>
            </a>
            </Link>
            <Link href="/mvp">
            <a className={styles.card}>
              <h2>Vote MVP & Stats &rarr;</h2>
              <p>Vote for MVP of the day, find in depth analysis of Banana Players.</p>
            </a>
            </Link>
          </div>
          
          
          </div>     
      }
           {
            !session &&
              <>
               <p className={styles.title}>Please Sign in</p>
               
              </>
           }
           
      </main>
       
       <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/hzethraeus/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Henric
        </a>
      </footer>
    </div>
  )
}
