import styles from "../styles/Home.module.css"; 
import { useSession } from 'next-auth/react';
import Header from '../components/Header';
import Head from 'next/head';

export default function MVP() {
    const { data: session, status } = useSession()
    const loading = status === "loading"
    return <div className={styles.container}>
    <Head>
      <title>Basket Bananas</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />

        <main className={styles.main}>
        {loading && <div className={styles.title}>Loading...</div>}
        {
            session && <>
             <h1>MVP</h1>

            <p>(Under construction)</p>
            </>
}{
            !session && <>
               <p className={styles.title}>Please Sign in</p>
              </>
           }


        </main>
        <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/hzethraeus/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Henric
        </a>
      </footer>
    </div>
}